# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1461/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1461/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vivid/vivid/VIVID3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vivid/vivid/VIVID3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1461/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1461/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.2.4-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1461/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1461/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1461/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1461/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1461/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1461/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vivid/vivid/VIVID3D/CMakeFiles /home/vivid/vivid/VIVID3D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vivid/vivid/VIVID3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vivid

# Build rule for target.
vivid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vivid
.PHONY : vivid

# fast build rule for target.
vivid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/build
.PHONY : vivid/fast

#=============================================================================
# Target rules for targets named voronoi

# Build rule for target.
voronoi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voronoi
.PHONY : voronoi

# fast build rule for target.
voronoi/fast:
	$(MAKE) $(MAKESILENT) -f lib/SurfacingAlgorithms/huji-rich-Elad3DFast/CMakeFiles/voronoi.dir/build.make lib/SurfacingAlgorithms/huji-rich-Elad3DFast/CMakeFiles/voronoi.dir/build
.PHONY : voronoi/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f lib/ImportExport/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build.make lib/ImportExport/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f lib/ImportExport/assimp/code/CMakeFiles/assimp.dir/build.make lib/ImportExport/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

lib/Decimate.o: lib/Decimate.cpp.o
.PHONY : lib/Decimate.o

# target to build an object file
lib/Decimate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/Decimate.cpp.o
.PHONY : lib/Decimate.cpp.o

lib/Decimate.i: lib/Decimate.cpp.i
.PHONY : lib/Decimate.i

# target to preprocess a source file
lib/Decimate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/Decimate.cpp.i
.PHONY : lib/Decimate.cpp.i

lib/Decimate.s: lib/Decimate.cpp.s
.PHONY : lib/Decimate.s

# target to generate assembly for a file
lib/Decimate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/Decimate.cpp.s
.PHONY : lib/Decimate.cpp.s

lib/ImportExport/lodepng/lodepng.o: lib/ImportExport/lodepng/lodepng.cpp.o
.PHONY : lib/ImportExport/lodepng/lodepng.o

# target to build an object file
lib/ImportExport/lodepng/lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/ImportExport/lodepng/lodepng.cpp.o
.PHONY : lib/ImportExport/lodepng/lodepng.cpp.o

lib/ImportExport/lodepng/lodepng.i: lib/ImportExport/lodepng/lodepng.cpp.i
.PHONY : lib/ImportExport/lodepng/lodepng.i

# target to preprocess a source file
lib/ImportExport/lodepng/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/ImportExport/lodepng/lodepng.cpp.i
.PHONY : lib/ImportExport/lodepng/lodepng.cpp.i

lib/ImportExport/lodepng/lodepng.s: lib/ImportExport/lodepng/lodepng.cpp.s
.PHONY : lib/ImportExport/lodepng/lodepng.s

# target to generate assembly for a file
lib/ImportExport/lodepng/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/ImportExport/lodepng/lodepng.cpp.s
.PHONY : lib/ImportExport/lodepng/lodepng.cpp.s

lib/MeshDecimation/mdMeshDecimator.o: lib/MeshDecimation/mdMeshDecimator.cpp.o
.PHONY : lib/MeshDecimation/mdMeshDecimator.o

# target to build an object file
lib/MeshDecimation/mdMeshDecimator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/MeshDecimation/mdMeshDecimator.cpp.o
.PHONY : lib/MeshDecimation/mdMeshDecimator.cpp.o

lib/MeshDecimation/mdMeshDecimator.i: lib/MeshDecimation/mdMeshDecimator.cpp.i
.PHONY : lib/MeshDecimation/mdMeshDecimator.i

# target to preprocess a source file
lib/MeshDecimation/mdMeshDecimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/MeshDecimation/mdMeshDecimator.cpp.i
.PHONY : lib/MeshDecimation/mdMeshDecimator.cpp.i

lib/MeshDecimation/mdMeshDecimator.s: lib/MeshDecimation/mdMeshDecimator.cpp.s
.PHONY : lib/MeshDecimation/mdMeshDecimator.s

# target to generate assembly for a file
lib/MeshDecimation/mdMeshDecimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/MeshDecimation/mdMeshDecimator.cpp.s
.PHONY : lib/MeshDecimation/mdMeshDecimator.cpp.s

lib/SurfacingAlgorithms/Voronoi.o: lib/SurfacingAlgorithms/Voronoi.cpp.o
.PHONY : lib/SurfacingAlgorithms/Voronoi.o

# target to build an object file
lib/SurfacingAlgorithms/Voronoi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/SurfacingAlgorithms/Voronoi.cpp.o
.PHONY : lib/SurfacingAlgorithms/Voronoi.cpp.o

lib/SurfacingAlgorithms/Voronoi.i: lib/SurfacingAlgorithms/Voronoi.cpp.i
.PHONY : lib/SurfacingAlgorithms/Voronoi.i

# target to preprocess a source file
lib/SurfacingAlgorithms/Voronoi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/SurfacingAlgorithms/Voronoi.cpp.i
.PHONY : lib/SurfacingAlgorithms/Voronoi.cpp.i

lib/SurfacingAlgorithms/Voronoi.s: lib/SurfacingAlgorithms/Voronoi.cpp.s
.PHONY : lib/SurfacingAlgorithms/Voronoi.s

# target to generate assembly for a file
lib/SurfacingAlgorithms/Voronoi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/lib/SurfacingAlgorithms/Voronoi.cpp.s
.PHONY : lib/SurfacingAlgorithms/Voronoi.cpp.s

src/Extra/Analysis.o: src/Extra/Analysis.cpp.o
.PHONY : src/Extra/Analysis.o

# target to build an object file
src/Extra/Analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Extra/Analysis.cpp.o
.PHONY : src/Extra/Analysis.cpp.o

src/Extra/Analysis.i: src/Extra/Analysis.cpp.i
.PHONY : src/Extra/Analysis.i

# target to preprocess a source file
src/Extra/Analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Extra/Analysis.cpp.i
.PHONY : src/Extra/Analysis.cpp.i

src/Extra/Analysis.s: src/Extra/Analysis.cpp.s
.PHONY : src/Extra/Analysis.s

# target to generate assembly for a file
src/Extra/Analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Extra/Analysis.cpp.s
.PHONY : src/Extra/Analysis.cpp.s

src/ImportExport/AssimpImportExport.o: src/ImportExport/AssimpImportExport.cpp.o
.PHONY : src/ImportExport/AssimpImportExport.o

# target to build an object file
src/ImportExport/AssimpImportExport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/AssimpImportExport.cpp.o
.PHONY : src/ImportExport/AssimpImportExport.cpp.o

src/ImportExport/AssimpImportExport.i: src/ImportExport/AssimpImportExport.cpp.i
.PHONY : src/ImportExport/AssimpImportExport.i

# target to preprocess a source file
src/ImportExport/AssimpImportExport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/AssimpImportExport.cpp.i
.PHONY : src/ImportExport/AssimpImportExport.cpp.i

src/ImportExport/AssimpImportExport.s: src/ImportExport/AssimpImportExport.cpp.s
.PHONY : src/ImportExport/AssimpImportExport.s

# target to generate assembly for a file
src/ImportExport/AssimpImportExport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/AssimpImportExport.cpp.s
.PHONY : src/ImportExport/AssimpImportExport.cpp.s

src/ImportExport/BlobData.o: src/ImportExport/BlobData.cpp.o
.PHONY : src/ImportExport/BlobData.o

# target to build an object file
src/ImportExport/BlobData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/BlobData.cpp.o
.PHONY : src/ImportExport/BlobData.cpp.o

src/ImportExport/BlobData.i: src/ImportExport/BlobData.cpp.i
.PHONY : src/ImportExport/BlobData.i

# target to preprocess a source file
src/ImportExport/BlobData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/BlobData.cpp.i
.PHONY : src/ImportExport/BlobData.cpp.i

src/ImportExport/BlobData.s: src/ImportExport/BlobData.cpp.s
.PHONY : src/ImportExport/BlobData.s

# target to generate assembly for a file
src/ImportExport/BlobData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/BlobData.cpp.s
.PHONY : src/ImportExport/BlobData.cpp.s

src/ImportExport/ColorMapToPng.o: src/ImportExport/ColorMapToPng.cpp.o
.PHONY : src/ImportExport/ColorMapToPng.o

# target to build an object file
src/ImportExport/ColorMapToPng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ColorMapToPng.cpp.o
.PHONY : src/ImportExport/ColorMapToPng.cpp.o

src/ImportExport/ColorMapToPng.i: src/ImportExport/ColorMapToPng.cpp.i
.PHONY : src/ImportExport/ColorMapToPng.i

# target to preprocess a source file
src/ImportExport/ColorMapToPng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ColorMapToPng.cpp.i
.PHONY : src/ImportExport/ColorMapToPng.cpp.i

src/ImportExport/ColorMapToPng.s: src/ImportExport/ColorMapToPng.cpp.s
.PHONY : src/ImportExport/ColorMapToPng.s

# target to generate assembly for a file
src/ImportExport/ColorMapToPng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ColorMapToPng.cpp.s
.PHONY : src/ImportExport/ColorMapToPng.cpp.s

src/ImportExport/ObjImportExport.o: src/ImportExport/ObjImportExport.cpp.o
.PHONY : src/ImportExport/ObjImportExport.o

# target to build an object file
src/ImportExport/ObjImportExport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ObjImportExport.cpp.o
.PHONY : src/ImportExport/ObjImportExport.cpp.o

src/ImportExport/ObjImportExport.i: src/ImportExport/ObjImportExport.cpp.i
.PHONY : src/ImportExport/ObjImportExport.i

# target to preprocess a source file
src/ImportExport/ObjImportExport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ObjImportExport.cpp.i
.PHONY : src/ImportExport/ObjImportExport.cpp.i

src/ImportExport/ObjImportExport.s: src/ImportExport/ObjImportExport.cpp.s
.PHONY : src/ImportExport/ObjImportExport.s

# target to generate assembly for a file
src/ImportExport/ObjImportExport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ImportExport/ObjImportExport.cpp.s
.PHONY : src/ImportExport/ObjImportExport.cpp.s

src/ModelBuilder/Animation.o: src/ModelBuilder/Animation.cpp.o
.PHONY : src/ModelBuilder/Animation.o

# target to build an object file
src/ModelBuilder/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Animation.cpp.o
.PHONY : src/ModelBuilder/Animation.cpp.o

src/ModelBuilder/Animation.i: src/ModelBuilder/Animation.cpp.i
.PHONY : src/ModelBuilder/Animation.i

# target to preprocess a source file
src/ModelBuilder/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Animation.cpp.i
.PHONY : src/ModelBuilder/Animation.cpp.i

src/ModelBuilder/Animation.s: src/ModelBuilder/Animation.cpp.s
.PHONY : src/ModelBuilder/Animation.s

# target to generate assembly for a file
src/ModelBuilder/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Animation.cpp.s
.PHONY : src/ModelBuilder/Animation.cpp.s

src/ModelBuilder/Line.o: src/ModelBuilder/Line.cpp.o
.PHONY : src/ModelBuilder/Line.o

# target to build an object file
src/ModelBuilder/Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Line.cpp.o
.PHONY : src/ModelBuilder/Line.cpp.o

src/ModelBuilder/Line.i: src/ModelBuilder/Line.cpp.i
.PHONY : src/ModelBuilder/Line.i

# target to preprocess a source file
src/ModelBuilder/Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Line.cpp.i
.PHONY : src/ModelBuilder/Line.cpp.i

src/ModelBuilder/Line.s: src/ModelBuilder/Line.cpp.s
.PHONY : src/ModelBuilder/Line.s

# target to generate assembly for a file
src/ModelBuilder/Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Line.cpp.s
.PHONY : src/ModelBuilder/Line.cpp.s

src/ModelBuilder/MarchingCubesSurface.o: src/ModelBuilder/MarchingCubesSurface.cpp.o
.PHONY : src/ModelBuilder/MarchingCubesSurface.o

# target to build an object file
src/ModelBuilder/MarchingCubesSurface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/MarchingCubesSurface.cpp.o
.PHONY : src/ModelBuilder/MarchingCubesSurface.cpp.o

src/ModelBuilder/MarchingCubesSurface.i: src/ModelBuilder/MarchingCubesSurface.cpp.i
.PHONY : src/ModelBuilder/MarchingCubesSurface.i

# target to preprocess a source file
src/ModelBuilder/MarchingCubesSurface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/MarchingCubesSurface.cpp.i
.PHONY : src/ModelBuilder/MarchingCubesSurface.cpp.i

src/ModelBuilder/MarchingCubesSurface.s: src/ModelBuilder/MarchingCubesSurface.cpp.s
.PHONY : src/ModelBuilder/MarchingCubesSurface.s

# target to generate assembly for a file
src/ModelBuilder/MarchingCubesSurface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/MarchingCubesSurface.cpp.s
.PHONY : src/ModelBuilder/MarchingCubesSurface.cpp.s

src/ModelBuilder/Mesh.o: src/ModelBuilder/Mesh.cpp.o
.PHONY : src/ModelBuilder/Mesh.o

# target to build an object file
src/ModelBuilder/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Mesh.cpp.o
.PHONY : src/ModelBuilder/Mesh.cpp.o

src/ModelBuilder/Mesh.i: src/ModelBuilder/Mesh.cpp.i
.PHONY : src/ModelBuilder/Mesh.i

# target to preprocess a source file
src/ModelBuilder/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Mesh.cpp.i
.PHONY : src/ModelBuilder/Mesh.cpp.i

src/ModelBuilder/Mesh.s: src/ModelBuilder/Mesh.cpp.s
.PHONY : src/ModelBuilder/Mesh.s

# target to generate assembly for a file
src/ModelBuilder/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Mesh.cpp.s
.PHONY : src/ModelBuilder/Mesh.cpp.s

src/ModelBuilder/Model.o: src/ModelBuilder/Model.cpp.o
.PHONY : src/ModelBuilder/Model.o

# target to build an object file
src/ModelBuilder/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Model.cpp.o
.PHONY : src/ModelBuilder/Model.cpp.o

src/ModelBuilder/Model.i: src/ModelBuilder/Model.cpp.i
.PHONY : src/ModelBuilder/Model.i

# target to preprocess a source file
src/ModelBuilder/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Model.cpp.i
.PHONY : src/ModelBuilder/Model.cpp.i

src/ModelBuilder/Model.s: src/ModelBuilder/Model.cpp.s
.PHONY : src/ModelBuilder/Model.s

# target to generate assembly for a file
src/ModelBuilder/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Model.cpp.s
.PHONY : src/ModelBuilder/Model.cpp.s

src/ModelBuilder/ModelComponent.o: src/ModelBuilder/ModelComponent.cpp.o
.PHONY : src/ModelBuilder/ModelComponent.o

# target to build an object file
src/ModelBuilder/ModelComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/ModelComponent.cpp.o
.PHONY : src/ModelBuilder/ModelComponent.cpp.o

src/ModelBuilder/ModelComponent.i: src/ModelBuilder/ModelComponent.cpp.i
.PHONY : src/ModelBuilder/ModelComponent.i

# target to preprocess a source file
src/ModelBuilder/ModelComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/ModelComponent.cpp.i
.PHONY : src/ModelBuilder/ModelComponent.cpp.i

src/ModelBuilder/ModelComponent.s: src/ModelBuilder/ModelComponent.cpp.s
.PHONY : src/ModelBuilder/ModelComponent.s

# target to generate assembly for a file
src/ModelBuilder/ModelComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/ModelComponent.cpp.s
.PHONY : src/ModelBuilder/ModelComponent.cpp.s

src/ModelBuilder/PointCloud.o: src/ModelBuilder/PointCloud.cpp.o
.PHONY : src/ModelBuilder/PointCloud.o

# target to build an object file
src/ModelBuilder/PointCloud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/PointCloud.cpp.o
.PHONY : src/ModelBuilder/PointCloud.cpp.o

src/ModelBuilder/PointCloud.i: src/ModelBuilder/PointCloud.cpp.i
.PHONY : src/ModelBuilder/PointCloud.i

# target to preprocess a source file
src/ModelBuilder/PointCloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/PointCloud.cpp.i
.PHONY : src/ModelBuilder/PointCloud.cpp.i

src/ModelBuilder/PointCloud.s: src/ModelBuilder/PointCloud.cpp.s
.PHONY : src/ModelBuilder/PointCloud.s

# target to generate assembly for a file
src/ModelBuilder/PointCloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/PointCloud.cpp.s
.PHONY : src/ModelBuilder/PointCloud.cpp.s

src/ModelBuilder/Shapes.o: src/ModelBuilder/Shapes.cpp.o
.PHONY : src/ModelBuilder/Shapes.o

# target to build an object file
src/ModelBuilder/Shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Shapes.cpp.o
.PHONY : src/ModelBuilder/Shapes.cpp.o

src/ModelBuilder/Shapes.i: src/ModelBuilder/Shapes.cpp.i
.PHONY : src/ModelBuilder/Shapes.i

# target to preprocess a source file
src/ModelBuilder/Shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Shapes.cpp.i
.PHONY : src/ModelBuilder/Shapes.cpp.i

src/ModelBuilder/Shapes.s: src/ModelBuilder/Shapes.cpp.s
.PHONY : src/ModelBuilder/Shapes.s

# target to generate assembly for a file
src/ModelBuilder/Shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Shapes.cpp.s
.PHONY : src/ModelBuilder/Shapes.cpp.s

src/ModelBuilder/StopMotionAnimation.o: src/ModelBuilder/StopMotionAnimation.cpp.o
.PHONY : src/ModelBuilder/StopMotionAnimation.o

# target to build an object file
src/ModelBuilder/StopMotionAnimation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/StopMotionAnimation.cpp.o
.PHONY : src/ModelBuilder/StopMotionAnimation.cpp.o

src/ModelBuilder/StopMotionAnimation.i: src/ModelBuilder/StopMotionAnimation.cpp.i
.PHONY : src/ModelBuilder/StopMotionAnimation.i

# target to preprocess a source file
src/ModelBuilder/StopMotionAnimation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/StopMotionAnimation.cpp.i
.PHONY : src/ModelBuilder/StopMotionAnimation.cpp.i

src/ModelBuilder/StopMotionAnimation.s: src/ModelBuilder/StopMotionAnimation.cpp.s
.PHONY : src/ModelBuilder/StopMotionAnimation.s

# target to generate assembly for a file
src/ModelBuilder/StopMotionAnimation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/StopMotionAnimation.cpp.s
.PHONY : src/ModelBuilder/StopMotionAnimation.cpp.s

src/ModelBuilder/SurfByFunc.o: src/ModelBuilder/SurfByFunc.cpp.o
.PHONY : src/ModelBuilder/SurfByFunc.o

# target to build an object file
src/ModelBuilder/SurfByFunc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/SurfByFunc.cpp.o
.PHONY : src/ModelBuilder/SurfByFunc.cpp.o

src/ModelBuilder/SurfByFunc.i: src/ModelBuilder/SurfByFunc.cpp.i
.PHONY : src/ModelBuilder/SurfByFunc.i

# target to preprocess a source file
src/ModelBuilder/SurfByFunc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/SurfByFunc.cpp.i
.PHONY : src/ModelBuilder/SurfByFunc.cpp.i

src/ModelBuilder/SurfByFunc.s: src/ModelBuilder/SurfByFunc.cpp.s
.PHONY : src/ModelBuilder/SurfByFunc.s

# target to generate assembly for a file
src/ModelBuilder/SurfByFunc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/SurfByFunc.cpp.s
.PHONY : src/ModelBuilder/SurfByFunc.cpp.s

src/ModelBuilder/Vivify.o: src/ModelBuilder/Vivify.cpp.o
.PHONY : src/ModelBuilder/Vivify.o

# target to build an object file
src/ModelBuilder/Vivify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Vivify.cpp.o
.PHONY : src/ModelBuilder/Vivify.cpp.o

src/ModelBuilder/Vivify.i: src/ModelBuilder/Vivify.cpp.i
.PHONY : src/ModelBuilder/Vivify.i

# target to preprocess a source file
src/ModelBuilder/Vivify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Vivify.cpp.i
.PHONY : src/ModelBuilder/Vivify.cpp.i

src/ModelBuilder/Vivify.s: src/ModelBuilder/Vivify.cpp.s
.PHONY : src/ModelBuilder/Vivify.s

# target to generate assembly for a file
src/ModelBuilder/Vivify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/Vivify.cpp.s
.PHONY : src/ModelBuilder/Vivify.cpp.s

src/ModelBuilder/VoronoiVolume.o: src/ModelBuilder/VoronoiVolume.cpp.o
.PHONY : src/ModelBuilder/VoronoiVolume.o

# target to build an object file
src/ModelBuilder/VoronoiVolume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/VoronoiVolume.cpp.o
.PHONY : src/ModelBuilder/VoronoiVolume.cpp.o

src/ModelBuilder/VoronoiVolume.i: src/ModelBuilder/VoronoiVolume.cpp.i
.PHONY : src/ModelBuilder/VoronoiVolume.i

# target to preprocess a source file
src/ModelBuilder/VoronoiVolume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/VoronoiVolume.cpp.i
.PHONY : src/ModelBuilder/VoronoiVolume.cpp.i

src/ModelBuilder/VoronoiVolume.s: src/ModelBuilder/VoronoiVolume.cpp.s
.PHONY : src/ModelBuilder/VoronoiVolume.s

# target to generate assembly for a file
src/ModelBuilder/VoronoiVolume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/ModelBuilder/VoronoiVolume.cpp.s
.PHONY : src/ModelBuilder/VoronoiVolume.cpp.s

src/Textures/ColorDefs.o: src/Textures/ColorDefs.cpp.o
.PHONY : src/Textures/ColorDefs.o

# target to build an object file
src/Textures/ColorDefs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Textures/ColorDefs.cpp.o
.PHONY : src/Textures/ColorDefs.cpp.o

src/Textures/ColorDefs.i: src/Textures/ColorDefs.cpp.i
.PHONY : src/Textures/ColorDefs.i

# target to preprocess a source file
src/Textures/ColorDefs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Textures/ColorDefs.cpp.i
.PHONY : src/Textures/ColorDefs.cpp.i

src/Textures/ColorDefs.s: src/Textures/ColorDefs.cpp.s
.PHONY : src/Textures/ColorDefs.s

# target to generate assembly for a file
src/Textures/ColorDefs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Textures/ColorDefs.cpp.s
.PHONY : src/Textures/ColorDefs.cpp.s

src/Utils/ConstrainedNumbers.o: src/Utils/ConstrainedNumbers.cpp.o
.PHONY : src/Utils/ConstrainedNumbers.o

# target to build an object file
src/Utils/ConstrainedNumbers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/ConstrainedNumbers.cpp.o
.PHONY : src/Utils/ConstrainedNumbers.cpp.o

src/Utils/ConstrainedNumbers.i: src/Utils/ConstrainedNumbers.cpp.i
.PHONY : src/Utils/ConstrainedNumbers.i

# target to preprocess a source file
src/Utils/ConstrainedNumbers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/ConstrainedNumbers.cpp.i
.PHONY : src/Utils/ConstrainedNumbers.cpp.i

src/Utils/ConstrainedNumbers.s: src/Utils/ConstrainedNumbers.cpp.s
.PHONY : src/Utils/ConstrainedNumbers.s

# target to generate assembly for a file
src/Utils/ConstrainedNumbers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/ConstrainedNumbers.cpp.s
.PHONY : src/Utils/ConstrainedNumbers.cpp.s

src/Utils/Logging/LogFile.o: src/Utils/Logging/LogFile.cpp.o
.PHONY : src/Utils/Logging/LogFile.o

# target to build an object file
src/Utils/Logging/LogFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/LogFile.cpp.o
.PHONY : src/Utils/Logging/LogFile.cpp.o

src/Utils/Logging/LogFile.i: src/Utils/Logging/LogFile.cpp.i
.PHONY : src/Utils/Logging/LogFile.i

# target to preprocess a source file
src/Utils/Logging/LogFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/LogFile.cpp.i
.PHONY : src/Utils/Logging/LogFile.cpp.i

src/Utils/Logging/LogFile.s: src/Utils/Logging/LogFile.cpp.s
.PHONY : src/Utils/Logging/LogFile.s

# target to generate assembly for a file
src/Utils/Logging/LogFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/LogFile.cpp.s
.PHONY : src/Utils/Logging/LogFile.cpp.s

src/Utils/Logging/ProgressBar.o: src/Utils/Logging/ProgressBar.cpp.o
.PHONY : src/Utils/Logging/ProgressBar.o

# target to build an object file
src/Utils/Logging/ProgressBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/ProgressBar.cpp.o
.PHONY : src/Utils/Logging/ProgressBar.cpp.o

src/Utils/Logging/ProgressBar.i: src/Utils/Logging/ProgressBar.cpp.i
.PHONY : src/Utils/Logging/ProgressBar.i

# target to preprocess a source file
src/Utils/Logging/ProgressBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/ProgressBar.cpp.i
.PHONY : src/Utils/Logging/ProgressBar.cpp.i

src/Utils/Logging/ProgressBar.s: src/Utils/Logging/ProgressBar.cpp.s
.PHONY : src/Utils/Logging/ProgressBar.s

# target to generate assembly for a file
src/Utils/Logging/ProgressBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Logging/ProgressBar.cpp.s
.PHONY : src/Utils/Logging/ProgressBar.cpp.s

src/Utils/Noisify.o: src/Utils/Noisify.cpp.o
.PHONY : src/Utils/Noisify.o

# target to build an object file
src/Utils/Noisify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Noisify.cpp.o
.PHONY : src/Utils/Noisify.cpp.o

src/Utils/Noisify.i: src/Utils/Noisify.cpp.i
.PHONY : src/Utils/Noisify.i

# target to preprocess a source file
src/Utils/Noisify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Noisify.cpp.i
.PHONY : src/Utils/Noisify.cpp.i

src/Utils/Noisify.s: src/Utils/Noisify.cpp.s
.PHONY : src/Utils/Noisify.s

# target to generate assembly for a file
src/Utils/Noisify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vivid.dir/build.make CMakeFiles/vivid.dir/src/Utils/Noisify.cpp.s
.PHONY : src/Utils/Noisify.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... assimp"
	@echo "... vivid"
	@echo "... voronoi"
	@echo "... zlibstatic"
	@echo "... lib/Decimate.o"
	@echo "... lib/Decimate.i"
	@echo "... lib/Decimate.s"
	@echo "... lib/ImportExport/lodepng/lodepng.o"
	@echo "... lib/ImportExport/lodepng/lodepng.i"
	@echo "... lib/ImportExport/lodepng/lodepng.s"
	@echo "... lib/MeshDecimation/mdMeshDecimator.o"
	@echo "... lib/MeshDecimation/mdMeshDecimator.i"
	@echo "... lib/MeshDecimation/mdMeshDecimator.s"
	@echo "... lib/SurfacingAlgorithms/Voronoi.o"
	@echo "... lib/SurfacingAlgorithms/Voronoi.i"
	@echo "... lib/SurfacingAlgorithms/Voronoi.s"
	@echo "... src/Extra/Analysis.o"
	@echo "... src/Extra/Analysis.i"
	@echo "... src/Extra/Analysis.s"
	@echo "... src/ImportExport/AssimpImportExport.o"
	@echo "... src/ImportExport/AssimpImportExport.i"
	@echo "... src/ImportExport/AssimpImportExport.s"
	@echo "... src/ImportExport/BlobData.o"
	@echo "... src/ImportExport/BlobData.i"
	@echo "... src/ImportExport/BlobData.s"
	@echo "... src/ImportExport/ColorMapToPng.o"
	@echo "... src/ImportExport/ColorMapToPng.i"
	@echo "... src/ImportExport/ColorMapToPng.s"
	@echo "... src/ImportExport/ObjImportExport.o"
	@echo "... src/ImportExport/ObjImportExport.i"
	@echo "... src/ImportExport/ObjImportExport.s"
	@echo "... src/ModelBuilder/Animation.o"
	@echo "... src/ModelBuilder/Animation.i"
	@echo "... src/ModelBuilder/Animation.s"
	@echo "... src/ModelBuilder/Line.o"
	@echo "... src/ModelBuilder/Line.i"
	@echo "... src/ModelBuilder/Line.s"
	@echo "... src/ModelBuilder/MarchingCubesSurface.o"
	@echo "... src/ModelBuilder/MarchingCubesSurface.i"
	@echo "... src/ModelBuilder/MarchingCubesSurface.s"
	@echo "... src/ModelBuilder/Mesh.o"
	@echo "... src/ModelBuilder/Mesh.i"
	@echo "... src/ModelBuilder/Mesh.s"
	@echo "... src/ModelBuilder/Model.o"
	@echo "... src/ModelBuilder/Model.i"
	@echo "... src/ModelBuilder/Model.s"
	@echo "... src/ModelBuilder/ModelComponent.o"
	@echo "... src/ModelBuilder/ModelComponent.i"
	@echo "... src/ModelBuilder/ModelComponent.s"
	@echo "... src/ModelBuilder/PointCloud.o"
	@echo "... src/ModelBuilder/PointCloud.i"
	@echo "... src/ModelBuilder/PointCloud.s"
	@echo "... src/ModelBuilder/Shapes.o"
	@echo "... src/ModelBuilder/Shapes.i"
	@echo "... src/ModelBuilder/Shapes.s"
	@echo "... src/ModelBuilder/StopMotionAnimation.o"
	@echo "... src/ModelBuilder/StopMotionAnimation.i"
	@echo "... src/ModelBuilder/StopMotionAnimation.s"
	@echo "... src/ModelBuilder/SurfByFunc.o"
	@echo "... src/ModelBuilder/SurfByFunc.i"
	@echo "... src/ModelBuilder/SurfByFunc.s"
	@echo "... src/ModelBuilder/Vivify.o"
	@echo "... src/ModelBuilder/Vivify.i"
	@echo "... src/ModelBuilder/Vivify.s"
	@echo "... src/ModelBuilder/VoronoiVolume.o"
	@echo "... src/ModelBuilder/VoronoiVolume.i"
	@echo "... src/ModelBuilder/VoronoiVolume.s"
	@echo "... src/Textures/ColorDefs.o"
	@echo "... src/Textures/ColorDefs.i"
	@echo "... src/Textures/ColorDefs.s"
	@echo "... src/Utils/ConstrainedNumbers.o"
	@echo "... src/Utils/ConstrainedNumbers.i"
	@echo "... src/Utils/ConstrainedNumbers.s"
	@echo "... src/Utils/Logging/LogFile.o"
	@echo "... src/Utils/Logging/LogFile.i"
	@echo "... src/Utils/Logging/LogFile.s"
	@echo "... src/Utils/Logging/ProgressBar.o"
	@echo "... src/Utils/Logging/ProgressBar.i"
	@echo "... src/Utils/Logging/ProgressBar.s"
	@echo "... src/Utils/Noisify.o"
	@echo "... src/Utils/Noisify.i"
	@echo "... src/Utils/Noisify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

