[build-system]
requires = [
    "setuptools>=61.0",
    "scikit-build>=0.15.0",
    "cmake>=3.24.1.1",
    "ninja>=1.10.2.4; platform_system!='Windows'",
    "python-dev-tools>=2022.5.27"
]
build-backend = "setuptools.build_meta"
